### ISSUE TITLE
Added sessionStorage Support

### ISSUE THREAD

**Issue by s0kil** [epswartz/graphpaper#5]
Added sessionStorage Support With Smart Checking and Restore options, For a better UX.

https://pastebin.com/vAR7QVA8

**Comment by epswartz** [comment]
Implemented, I tweaked it a bit so the user didn't have to confirm it - that felt to me as though it was redundant to the clear button.

Thanks!

**Comment by s0kil** [comment]
Heck Yeah!, Working on adding more features, Like touch support.
